# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-07 10:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0002_auto_20171107_1454'),
    ]

    operations = [
        migrations.AlterField(
            model_name='portal',
            name='user',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='User'),
        ),
    ]
