version: '2'

services:

  web:
    restart: always
    build: .
    command: bash -c "python3 manage.py migrate; python3 manage.py runserver 0.0.0.0:8000"
    volumes:
      - .:/project
    ports:
      - "8000:8000"
    links:
      - celery
    depends_on:
      - celery

  redis:
    image: redis

  celery:
    image: celery
    restart: always
    build: .
    volumes:
      - .:/project
    command: bash -c "python manage.py celery worker -B --loglevel=debug --concurrency=4"
    links:
      - redis
    depends_on:
      - redis